### ISSUE TITLE
AttributeError: module 'pandas._libs.tslib' has no attribute 'NaTType'

### ISSUE THREAD

**Issue by neutralino1** [instacart/jardin#39]
```
>>> Manifest.insert(values={'data': '{"dataset":"blabla","labeled_at_ts":"2018-10-01T12:21:14.93962Z"}'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hlo/Cruise/terrarium/jardin/venv/lib/python3.6/site-packages/jardin/model.py", line 336, in insert
    results = self.db_adapter(role='master').insert(**kwargs)
  File "/Users/hlo/Cruise/terrarium/jardin/venv/lib/python3.6/site-packages/jardin/database/__init__.py", line 93, in insert
    return self.write(InsertQueryBuilder, **kwargs)
  File "/Users/hlo/Cruise/terrarium/jardin/venv/lib/python3.6/site-packages/jardin/database/__init__.py", line 63, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/hlo/Cruise/terrarium/jardin/venv/lib/python3.6/site-packages/jardin/database/__init__.py", line 83, in write
    query = query_builder(**kwargs).query
  File "/Users/hlo/Cruise/terrarium/jardin/venv/lib/python3.6/site-packages/memoized_property.py", line 40, in fget_memoized
    setattr(self, attr_name, fget(self))
  File "/Users/hlo/Cruise/terrarium/jardin/venv/lib/python3.6/site-packages/jardin/query_builders.py", line 320, in query
    [self.list_wrap(ext) for ext in self.value_extrapolators]
  File "/Users/hlo/Cruise/terrarium/jardin/venv/lib/python3.6/site-packages/memoized_property.py", line 40, in fget_memoized
    setattr(self, attr_name, fget(self))
  File "/Users/hlo/Cruise/terrarium/jardin/venv/lib/python3.6/site-packages/jardin/query_builders.py", line 289, in value_extrapolators
    return [[self.extrapolator(fa) for fa in v.keys()] for v in self.values_list]
  File "/Users/hlo/Cruise/terrarium/jardin/venv/lib/python3.6/site-packages/memoized_property.py", line 40, in fget_memoized
    setattr(self, attr_name, fget(self))
  File "/Users/hlo/Cruise/terrarium/jardin/venv/lib/python3.6/site-packages/jardin/query_builders.py", line 277, in values_list
    if isinstance(v, pd._libs.tslib.NaTType):
AttributeError: module 'pandas._libs.tslib' has no attribute 'NaTType'```

**Comment by mathieuripert** [comment]
fixed by https://github.com/instacart/jardin/pull/44
